version: "3.9"
services:
  openliberty-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9080:9080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./server.xml:/app/config/server.xml
      - ~/.m2:/root/.m2
    command: mvn liberty:dev