FROM maven:3.9.6-eclipse-temurin-17 AS dev

WORKDIR /app

# Copiamos solo POM primero para cache de dependencias
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiamos scripts y configs necesarios
COPY src src
COPY server.xml /config/server.xml

# Comando por defecto: dev mode
CMD ["mvn", "liberty:dev"]