# Como base se toma una imagen de open liberty ligera.
FROM open-liberty:kernel-slim-java17-openj9

# Cambiamos al usuario root para instalar dependencias de testing.
USER root
RUN apt-get update
RUN apt-get install net-tools -y

#Instalar Features.
RUN featureUtility installFeature \
    jakartaee-10.0 \
    microprofile-7.0 \
    passwordUtilities-1.1 \
    ssl-1.0

# Copiar configuracion de Open Liberty.
#COPY server.xml /opt/ol/wlp/usr/servers/defaultServer/
ADD https://raw.githubusercontent.com/BlackPixl/WorkShopDocker/refs/heads/main/server.xml /opt/ol/wlp/usr/servers/defaultServer/

# Copiar Aplicaciones al directorio de apps.
COPY guide-mongodb-intro.war /opt/ol/wlp/usr/servers/defaultServer/apps/
COPY certs/truststore.p12 /opt/ol/wlp/output/defaultServer/resources/security/truststore.p12

CMD ["server", "run", "defaultServer"]
ENTRYPOINT ["server", "run", "defaultServer"]

# CMD vs ENTRYPOINT
# verisones de Dockerfile para cada una de las opciones CMD Entrypoint, copy, add.

